FROM node:6

WORKDIR /service

CMD ["npm", "start"]

RUN mkdir -p /service \
  && apt-get update && apt-get install apt-transport-https \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update && apt-get install yarn \
  && yarn global add nodemon node-gyp typescript

COPY ./ /service/

RUN npm install