module.exports.ag_ref_atma_components_v06 = {
  'Project': {
    'componentName': 'Team Agile Leadership and Collaboration - Projects',
    'practiceNumber': [2, 2, 3, 1, 3],
    'assessedComponents': [
      {
        'principleId': 1,
        'principleName': 'Collaboration and Teamwork',
        'practiceId': 1,
        'practiceName': 'Standups',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 1,
        'principleName': 'Collaboration and Teamwork',
        'practiceId': 2,
        'practiceName': 'Walls of Work',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 3,
        'practiceName': 'Engaging the Product Owner',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 4,
        'practiceName': 'Backlog Refinement',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Flexible, Adaptive and Continuously Improving',
        'practiceId': 5,
        'practiceName': 'Release and Iteration Planning',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Flexible, Adaptive and Continuously Improving',
        'practiceId': 6,
        'practiceName': 'Retrospectives',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Flexible, Adaptive and Continuously Improving',
        'practiceId': 7,
        'practiceName': 'Work Estimation (Relative Estimates)',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 4,
        'principleName': 'Iterative and Fast',
        'practiceId': 8,
        'practiceName': 'Story Cards',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Empowered and Self Directed Teams',
        'practiceId': 9,
        'practiceName': 'Stable Cross-Functional Teams',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Empowered and Self Directed Teams',
        'practiceId': 10,
        'practiceName': 'Social Contract',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Empowered and Self Directed Teams',
        'practiceId': 11,
        'practiceName': 'Risk and Issue Management',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
    ],
    'currentScore': 0,
    'targetScore': 0
  },
  'Operations': {
    'componentName': 'Team Agile Leadership and Collaboration - Operations',
    'practiceNumber': [2, 4, 2, 1, 2],
    'assessedComponents': [
      {
        'principleId': 1,
        'principleName': 'Collaboration and Teamwork',
        'practiceId': 1,
        'practiceName': 'Standups',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '0',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 1,
        'principleName': 'Collaboration and Teamwork',
        'practiceId': 2,
        'practiceName': 'Walls of Work',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 3,
        'practiceName': 'Value Stream Mapping',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 4,
        'practiceName': 'Engaging the Product or Process Owner',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 5,
        'practiceName': 'Backlog Refinement',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Focus on the Customer and Business Value',
        'practiceId': 6,
        'practiceName': 'Process Quality',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Flexible, Adaptive and Continuously Improving',
        'practiceId': 7,
        'practiceName': 'Retrospectives',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Flexible, Adaptive and Continuously Improving',
        'practiceId': 8,
        'practiceName': 'Kaizen and Continuous Improvement',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 4,
        'principleName': 'Iterative and Fast',
        'practiceId': 9,
        'practiceName': 'Kanban',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Empowered and Self Directed Teams',
        'practiceId': 10,
        'practiceName': 'Stable Cross-Functional Teams',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Empowered and Self Directed Teams',
        'practiceId': 11,
        'practiceName': 'Social Contract',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      }
    ],
    'currentScore': 0,
    'targetScore': 0
  },
  'Delivery': {
    'componentName': 'Team Delivery',
    'practiceNumber': [4, 1, 1, 1, 1],
    'assessedComponents': [
      {
        'principleId': 1,
        'principleName': 'Continuous Development',
        'practiceId': 1,
        'practiceName': 'Automated builds & Continuous Integration',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 1,
        'principleName': 'Continuous Development',
        'practiceId': 2,
        'practiceName': 'Managing Technical Debt',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 1,
        'principleName': 'Continuous Development',
        'practiceId': 3,
        'practiceName': 'Dev & Ops Collaboration / Shared Understanding',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 1,
        'principleName': 'Continuous Development',
        'practiceId': 4,
        'practiceName': 'Infrastructure Automation / Provisioning',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 2,
        'principleName': 'Continuous Testing',
        'practiceId': 5,
        'practiceName': 'Automated Testing',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 3,
        'principleName': 'Continuous Release & Deployment',
        'practiceId': 6,
        'practiceName': 'Automated Deployments',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 4,
        'principleName': 'Continuous Feedback & Optimization',
        'practiceId': 7,
        'practiceName': 'Customer Feedback',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      },
      {
        'principleId': 5,
        'principleName': 'Continuous Monitoring',
        'practiceId': 8,
        'practiceName': 'Monitoring of Environments',
        'currentLevelName': '',
        'currentScore': 0,
        'targetLevelName': '',
        'targetScore': 0,
        'assessorLevel': '',
        'assessorTarget': 0,
        'improveDescription': '',
        'assessorComment': ''
      }
    ],
    'currentScore': 0,
    'targetScore': 0
  }
};
